In [ ]:
import pandas as pd
#read dataset using pd .read_csv(csv_path)
df=pd.read_csv('/content/train.csv')
#1. Load the Titanic dataset into a DataFrame named df .

In [ ]:
#2. Display the first 10 rows of the dataset.
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
#3. Display the last 7 rows of the dataset.
df.tail(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

In [ ]:
#4. Show 5 random rows from the dataset.
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
677,678,1,3,"Turja, Miss. Anna Sofia",female,18.0,0,0,4138,9.8417,NaN,S
375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,NaN,1,0,PC 17604,82.1708,NaN,C
223,224,0,3,"Nenkoff, Mr. Christo",male,NaN,0,0,349234,7.8958,NaN,S
347,348,1,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,NaN,1,0,386525,16.1000,NaN,S
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,NaN,S

In [ ]:
#5. Find the total number of rows and columns in the dataset.
rows,colums=df.shape
print(rows)
print(colums)

891
12

In [ ]:
#6. Print all column names.
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
#7. Display complete information about the dataset using info() .
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
#9. Create a new DataFrame named df_small containing only the first 20 rows.
df_small=df[['Name','Age','Sex','Fare']]
df_small

                                                  Name   Age     Sex     Fare
0                              Braund, Mr. Owen Harris  22.0    male   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female  71.2833
2                               Heikkinen, Miss. Laina  26.0  female   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female  53.1000
4                             Allen, Mr. William Henry  35.0    male   8.0500
..                                                 ...   ...     ...      ...
886                              Montvila, Rev. Juozas  27.0    male  13.0000
887                       Graham, Miss. Margaret Edith  19.0  female  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female  23.4500
889                              Behr, Mr. Karl Howell  26.0    male  30.0000
890                                Dooley, Mr. Patrick  32.0    male   7.7500

[891 rows x 4 columns]

In [ ]:
#10. Create another DataFrame containing only the columns Name , Age , Sex , and Fare .

new_df = df[['Name', 'Age', 'Sex', 'Fare']]
new_df

                                                  Name   Age     Sex     Fare
0                              Braund, Mr. Owen Harris  22.0    male   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female  71.2833
2                               Heikkinen, Miss. Laina  26.0  female   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female  53.1000
4                             Allen, Mr. William Henry  35.0    male   8.0500
..                                                 ...   ...     ...      ...
886                              Montvila, Rev. Juozas  27.0    male  13.0000
887                       Graham, Miss. Margaret Edith  19.0  female  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female  23.4500
889                              Behr, Mr. Karl Howell  26.0    male  30.0000
890                                Dooley, Mr. Patrick  32.0    male   7.7500

[891 rows x 4 columns]

In [ ]:
#11. Select only the Age column.
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
#12. Select the columns Name , Pclass , and Survived .
df[['Name' , 'Pclass' , 'Survived']]

                                                  Name  Pclass  Survived
0                              Braund, Mr. Owen Harris       3         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1         1
2                               Heikkinen, Miss. Laina       3         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1         1
4                             Allen, Mr. William Henry       3         0
..                                                 ...     ...       ...
886                              Montvila, Rev. Juozas       2         0
887                       Graham, Miss. Margaret Edith       1         1
888           Johnston, Miss. Catherine Helen "Carrie"       3         0
889                              Behr, Mr. Karl Howell       1         1
890                                Dooley, Mr. Patrick       3         0

[891 rows x 3 columns]

In [ ]:
#13. Select the first row using iloc .
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
#14. Select rows 10 to 20 using iloc .
df.iloc[10:21]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S

In [ ]:
#15. Select rows 50 to 60 and columns Name and Fare .
df.iloc[[50,60],[3,9]]

In [ ]:
df.loc[100,'Name']

'Petranec, Miss. Matilda'

In [ ]:
#17. Select the last 15 rows of the dataset.
df.tail(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#18. Select all passengers whose names start with the letter A .
print(df[df['Name'].str.startswith('A')]['Name'])

4                               Allen, Mr. William Henry
13                           Andersson, Mr. Anders Johan
25     Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
40        Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
49         Arnold-Franchi, Mrs. Josef (Josefine Franchi)
68                       Andersson, Miss. Erna Alexandra
91                            Andreasson, Mr. Paul Edvin
114                                Attalah, Miss. Malake
119                    Andersson, Miss. Ellis Anna Maria
144                           Andrew, Mr. Edgardo Samuel
146         Andersson, Mr. August Edvard ("Wennerstrom")
182                Asplund, Master. Clarence Gustaf Hugo
192      Andersen-Jensen, Miss. Carla Christine Nielsine
207                          Albimona, Mr. Nassef Cassem
210                                       Ali, Mr. Ahmed
233                       Asplund, Miss. Lillian Gertrud
244                                 Attalah, Mr. Sleiman
261                    Asplund, Master. Edvin Rojj Felix
275                    Andrews, Miss. Kornelia Theodosia
279                     Abbott, Mrs. Stanton (Rosa Hunt)
297                         Allison, Miss. Helen Loraine
305                       Allison, Master. Hudson Trevor
308                                  Abelson, Mr. Samuel
353                            Arnold-Franchi, Mr. Josef
363                                      Asim, Mr. Adola
365                       Adahl, Mr. Mauritz Nils Martin
369                        Aubart, Mme. Leontine Pauline
401                                      Adams, Mr. John
460                                  Anderson, Mr. Harry
493                              Artagaveytia, Mr. Ramon
498      Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
518    Angle, Mrs. William A (Florence "Mary" Agnes H...
541                 Andersson, Miss. Ingeborg Constanzia
542                    Andersson, Miss. Sigrid Elisabeth
571        Appleton, Mrs. Edward Dale (Charlotte Lamson)
610    Andersson, Mrs. Anders Johan (Alfrida Konstant...
700    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
730                        Allen, Miss. Elisabeth Walton
746                          Abbott, Mr. Rossmore Edward
780                                 Ayoub, Miss. Banoura
784                                     Ali, Mr. William
806                               Andrews, Mr. Thomas Jr
810                               Alexander, Mr. William
813                   Andersson, Miss. Ebba Iris Alfrida
833                               Augustsson, Mr. Albert
834                               Allum, Mr. Owen George
840                          Alhomaki, Mr. Ilmari Rudolf
845                                  Abbing, Mr. Anthony
850              Andersson, Master. Sigvard Harald Elias
855                           Aks, Mrs. Sam (Leah Rosen)
874                Abelson, Mrs. Samuel (Hannah Wizosky)
Name: Name, dtype: object

In [ ]:
#19. Select the Fare values of the first 25 passengers.
print([df['Fare'].head(25)])

[0      7.2500
1     71.2833
2      7.9250
3     53.1000
4      8.0500
5      8.4583
6     51.8625
7     21.0750
8     11.1333
9     30.0708
10    16.7000
11    26.5500
12     8.0500
13    31.2750
14     7.8542
15    16.0000
16    29.1250
17    13.0000
18    18.0000
19     7.2250
20    26.0000
21    13.0000
22     8.0292
23    35.5000
24    21.0750
Name: Fare, dtype: float64]

In [ ]:
#20. Select rows where PassengerId is between 200 and 220.

print(df[(df['PassengerId'] >= 200) & (df['PassengerId'] <= 220)])

     PassengerId  Survived  Pclass                                    Name  \
199          200         0       2  Yrois, Miss. Henriette ("Mrs Harbeck")
200          201         0       3          Vande Walle, Mr. Nestor Cyriel
201          202         0       3                     Sage, Mr. Frederick
202          203         0       3              Johanson, Mr. Jakob Alfred
203          204         0       3                    Youseff, Mr. Gerious
204          205         1       3                Cohen, Mr. Gurshon "Gus"
205          206         0       3              Strom, Miss. Telma Matilda
206          207         0       3              Backstrom, Mr. Karl Alfred
207          208         1       3             Albimona, Mr. Nassef Cassem
208          209         1       3               Carr, Miss. Helen "Ellen"
209          210         1       1                        Blank, Mr. Henry
210          211         0       3                          Ali, Mr. Ahmed
211          212         1       2              Cameron, Miss. Clear Annie
212          213         0       3                  Perkin, Mr. John Henry
213          214         0       2             Givard, Mr. Hans Kristensen
214          215         0       3                     Kiernan, Mr. Philip
215          216         1       1                 Newell, Miss. Madeleine
216          217         1       3                  Honkanen, Miss. Eliina
217          218         0       2            Jacobsohn, Mr. Sidney Samuel
218          219         1       1                   Bazzani, Miss. Albina
219          220         0       2                      Harris, Mr. Walter

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
199  female  24.0      0      0              248747   13.0000   NaN        S
200    male  28.0      0      0              345770    9.5000   NaN        S
201    male   NaN      8      2            CA. 2343   69.5500   NaN        S
202    male  34.0      0      0             3101264    6.4958   NaN        S
203    male  45.5      0      0                2628    7.2250   NaN        C
204    male  18.0      0      0            A/5 3540    8.0500   NaN        S
205  female   2.0      0      1              347054   10.4625    G6        S
206    male  32.0      1      0             3101278   15.8500   NaN        S
207    male  26.0      0      0                2699   18.7875   NaN        C
208  female  16.0      0      0              367231    7.7500   NaN        Q
209    male  40.0      0      0              112277   31.0000   A31        C
210    male  24.0      0      0  SOTON/O.Q. 3101311    7.0500   NaN        S
211  female  35.0      0      0        F.C.C. 13528   21.0000   NaN        S
212    male  22.0      0      0           A/5 21174    7.2500   NaN        S
213    male  30.0      0      0              250646   13.0000   NaN        S
214    male   NaN      1      0              367229    7.7500   NaN        Q
215  female  31.0      1      0               35273  113.2750   D36        C
216  female  27.0      0      0    STON/O2. 3101283    7.9250   NaN        S
217    male  42.0      1      0              243847   27.0000   NaN        S
218  female  32.0      0      0               11813   76.2917   D15        C
219    male  30.0      0      0           W/C 14208   10.5000   NaN        S

In [ ]:
df['Family_Size']=df['SibSp']+df['Parch']+1
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [ ]:
#32. Create a column Fare_with_Tax = Fare * 1.18 .
df['Fare_with_Tax']=df['Fare']*1.18
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,8.555000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,84.114294
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,9.351500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,62.658000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,9.499000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,15.340000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,35.400000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,27.671000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,35.400000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,9.145000

In [ ]:
#33. Create a column Is_Child that is True if age is less than 18.
df['Is_Child']=df['Age']<18
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,8.555000,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,84.114294,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,9.351500,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,62.658000,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,9.499000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,15.340000,False
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,35.400000,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,27.671000,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,35.400000,False
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,9.145000,False

In [ ]:
#34. Create a column Name_Length containing the length of each passenger's name.
df['Name_Length']=df['Name'].str.len()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child,Name_Length
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,8.555000,False,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,84.114294,False,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,9.351500,False,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,62.658000,False,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,9.499000,False,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,15.340000,False,21
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,35.400000,False,28
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,27.671000,False,40
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,35.400000,False,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,9.145000,False,19

In [ ]:
#35. Create a column Fare_Category where:
#Fare > 100 → Very High
#Fare > 50 → High
#Otherwise → Low

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child,Name_Length,Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,8.555000,False,23,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,84.114294,False,51,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,9.351500,False,22,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,62.658000,False,44,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,9.499000,False,24,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,15.340000,False,21,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,35.400000,False,28,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,27.671000,False,40,Low
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,35.400000,False,21,Low
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,9.145000,False,19,Low

In [ ]:
#36. Increase all fares by 10%.
df['Fare']=df['Fare']*1.10
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child,Name_Length,Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.97500,NaN,S,2,8.555000,False,23,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,78.41163,C85,C,2,84.114294,False,51,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,8.71750,NaN,S,1,9.351500,False,22,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,58.41000,C123,S,2,62.658000,False,44,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.85500,NaN,S,1,9.499000,False,24,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,14.30000,NaN,S,1,15.340000,False,21,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,33.00000,B42,S,1,35.400000,False,28,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,25.79500,NaN,S,4,27.671000,False,40,Low
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,33.00000,C148,C,1,35.400000,False,21,Low
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,8.52500,NaN,Q,1,9.145000,False,19,Low

In [ ]:
#38. Convert values in Sex from male/female to M/F .
df['Sex']=df['Sex'].map({'male':'M','female':'F'})
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child,Name_Length,Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.97500,NaN,S,2,8.555000,False,23,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,78.41163,C85,C,2,84.114294,False,51,High
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,8.71750,NaN,S,1,9.351500,False,22,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,58.41000,C123,S,2,62.658000,False,44,High
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.85500,NaN,S,1,9.499000,False,24,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27.0,0,0,211536,14.30000,NaN,S,1,15.340000,False,21,Low
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.0,0,0,112053,33.00000,B42,S,1,35.400000,False,28,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,25.79500,NaN,S,4,27.671000,False,40,Low
889,890,1,1,"Behr, Mr. Karl Howell",M,26.0,0,0,111369,33.00000,C148,C,1,35.400000,False,21,Low
890,891,0,3,"Dooley, Mr. Patrick",M,32.0,0,0,370376,8.52500,NaN,Q,1,9.145000,False,19,Low

In [ ]:
#39. Set the fare of the first passenger to 999.
df.loc[0,'Fare']=999
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child,Name_Length,Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,999.00000,NaN,S,2,8.555000,False,23,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,78.41163,C85,C,2,84.114294,False,51,High
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,8.71750,NaN,S,1,9.351500,False,22,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,58.41000,C123,S,2,62.658000,False,44,High
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.85500,NaN,S,1,9.499000,False,24,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27.0,0,0,211536,14.30000,NaN,S,1,15.340000,False,21,Low
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.0,0,0,112053,33.00000,B42,S,1,35.400000,False,28,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,25.79500,NaN,S,4,27.671000,False,40,Low
889,890,1,1,"Behr, Mr. Karl Howell",M,26.0,0,0,111369,33.00000,C148,C,1,35.400000,False,21,Low
890,891,0,3,"Dooley, Mr. Patrick",M,32.0,0,0,370376,8.52500,NaN,Q,1,9.145000,False,19,Low

In [ ]:
#40. Increase the age of all passengers by 1 year.
df['Age']=df['Age']+1
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_with_Tax,Is_Child,Name_Length,Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",M,24.0,1,0,A/5 21171,999.00000,NaN,S,2,8.555000,False,23,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,40.0,1,0,PC 17599,78.41163,C85,C,2,84.114294,False,51,High
2,3,1,3,"Heikkinen, Miss. Laina",F,28.0,0,0,STON/O2. 3101282,8.71750,NaN,S,1,9.351500,False,22,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,37.0,1,0,113803,58.41000,C123,S,2,62.658000,False,44,High
4,5,0,3,"Allen, Mr. William Henry",M,37.0,0,0,373450,8.85500,NaN,S,1,9.499000,False,24,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,29.0,0,0,211536,14.30000,NaN,S,1,15.340000,False,21,Low
887,888,1,1,"Graham, Miss. Margaret Edith",F,21.0,0,0,112053,33.00000,B42,S,1,35.400000,False,28,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,25.79500,NaN,S,4,27.671000,False,40,Low
889,890,1,1,"Behr, Mr. Karl Howell",M,28.0,0,0,111369,33.00000,C148,C,1,35.400000,False,21,Low
890,891,0,3,"Dooley, Mr. Patrick",M,34.0,0,0,370376,8.52500,NaN,Q,1,9.145000,False,19,Low

In [ ]:
import pandas as pd



# Creating the dataset with the added Gender column
data = {
    'Student_ID': list(range(101, 116)),
    'Name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Eva',
        'Frank', 'Grace', 'Henry', 'Ivy', 'Jack',
        'Karl', 'Liam', 'Mia', 'Noah', 'Olivia'
    ],
    'Age': [20, 21, 19, 22, 20, 23, 21, 22, 20, 19, 21, 22, 20, 21, 19],
    'Gender': [
        'Female', 'Male', 'Male', 'Male', 'Female',
        'Male', 'Female', 'Male', 'Female', 'Male',
        'Male', 'Male', 'Female', 'Male', 'Female'
    ],
    'Major': [
        'Computer Science', 'Mathematics', 'Physics', 'Biology', 'Chemistry',
        'Computer Science', 'Mathematics', 'Physics', 'Biology', 'Chemistry',
        'Computer Science', 'Mathematics', 'Physics', 'Biology', 'Chemistry'
    ],
    'GPA': [3.8, 3.2, 3.9, 2.8, 3.5, 3.6, 3.1, 3.7, 3.4, 2.9, 3.9, 3.3, 4.0, 3.0, 3.6]
}

df = pd.DataFrame(data)
df

    Student_ID     Name  Age  Gender             Major  GPA
0          101    Alice   20  Female  Computer Science  3.8
1          102      Bob   21    Male       Mathematics  3.2
2          103  Charlie   19    Male           Physics  3.9
3          104    David   22    Male           Biology  2.8
4          105      Eva   20  Female         Chemistry  3.5
5          106    Frank   23    Male  Computer Science  3.6
6          107    Grace   21  Female       Mathematics  3.1
7          108    Henry   22    Male           Physics  3.7
8          109      Ivy   20  Female           Biology  3.4
9          110     Jack   19    Male         Chemistry  2.9
10         111     Karl   21    Male  Computer Science  3.9
11         112     Liam   22    Male       Mathematics  3.3
12         113      Mia   20  Female           Physics  4.0
13         114     Noah   21    Male           Biology  3.0
14         115   Olivia   19  Female         Chemistry  3.6